// flow-typed signature: cbb999bd7527b8a652e4de177dbd0c1c
// flow-typed version: <<STUB>>/material-ui_vlatest/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "material-ui" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "material-ui/AppBar/AppBar" {
  declare module.exports: any
}

declare module "material-ui/AppBar/index" {
  declare module.exports: any
}

declare module "material-ui/Avatar/Avatar" {
  declare module.exports: any
}

declare module "material-ui/Avatar/index" {
  declare module.exports: any
}

declare module "material-ui/Badge/Badge" {
  declare module.exports: any
}

declare module "material-ui/Badge/index" {
  declare module.exports: any
}

declare module "material-ui/BottomNavigation/BottomNavigation" {
  declare module.exports: any
}

declare module "material-ui/BottomNavigation/BottomNavigationButton" {
  declare module.exports: any
}

declare module "material-ui/BottomNavigation/index" {
  declare module.exports: any
}

declare module "material-ui/Button/Button" {
  declare module.exports: any
}

declare module "material-ui/Button/index" {
  declare module.exports: any
}

declare module "material-ui/Card/Card" {
  declare module.exports: any
}

declare module "material-ui/Card/CardActions" {
  declare module.exports: any
}

declare module "material-ui/Card/CardContent" {
  declare module.exports: any
}

declare module "material-ui/Card/CardHeader" {
  declare module.exports: any
}

declare module "material-ui/Card/CardMedia" {
  declare module.exports: any
}

declare module "material-ui/Card/index" {
  declare module.exports: any
}

declare module "material-ui/Checkbox/Checkbox" {
  declare module.exports: any
}

declare module "material-ui/Checkbox/index" {
  declare module.exports: any
}

declare module "material-ui/Checkbox/LabelCheckbox" {
  declare module.exports: any
}

declare module "material-ui/Chip/Chip" {
  declare module.exports: any
}

declare module "material-ui/Chip/index" {
  declare module.exports: any
}

declare module "material-ui/Dialog/Dialog" {
  declare module.exports: any
}

declare module "material-ui/Dialog/DialogActions" {
  declare module.exports: any
}

declare module "material-ui/Dialog/DialogContent" {
  declare module.exports: any
}

declare module "material-ui/Dialog/DialogContentText" {
  declare module.exports: any
}

declare module "material-ui/Dialog/DialogTitle" {
  declare module.exports: any
}

declare module "material-ui/Dialog/index" {
  declare module.exports: any
}

declare module "material-ui/Dialog/withResponsiveFullScreen" {
  declare module.exports: any
}

declare module "material-ui/Divider/Divider" {
  declare module.exports: any
}

declare module "material-ui/Divider/index" {
  declare module.exports: any
}

declare module "material-ui/Drawer/Drawer" {
  declare module.exports: any
}

declare module "material-ui/Drawer/index" {
  declare module.exports: any
}

declare module "material-ui/Form/FormControl" {
  declare module.exports: any
}

declare module "material-ui/Form/FormGroup" {
  declare module.exports: any
}

declare module "material-ui/Form/FormHelperText" {
  declare module.exports: any
}

declare module "material-ui/Form/FormLabel" {
  declare module.exports: any
}

declare module "material-ui/Form/index" {
  declare module.exports: any
}

declare module "material-ui/Grid/Grid" {
  declare module.exports: any
}

declare module "material-ui/Grid/index" {
  declare module.exports: any
}

declare module "material-ui/Hidden/Hidden" {
  declare module.exports: any
}

declare module "material-ui/Hidden/HiddenJs" {
  declare module.exports: any
}

declare module "material-ui/Hidden/index" {
  declare module.exports: any
}

declare module "material-ui/Hidden/types" {
  declare module.exports: any
}

declare module "material-ui/Icon/Icon" {
  declare module.exports: any
}

declare module "material-ui/Icon/index" {
  declare module.exports: any
}

declare module "material-ui/IconButton/IconButton" {
  declare module.exports: any
}

declare module "material-ui/IconButton/index" {
  declare module.exports: any
}

declare module "material-ui/index.es" {
  declare module.exports: any
}

declare module "material-ui/Input/index" {
  declare module.exports: any
}

declare module "material-ui/Input/Input" {
  declare module.exports: any
}

declare module "material-ui/Input/InputLabel" {
  declare module.exports: any
}

declare module "material-ui/Input/Textarea" {
  declare module.exports: any
}

declare module "material-ui/internal/Backdrop" {
  declare module.exports: any
}

declare module "material-ui/internal/ButtonBase" {
  declare module.exports: any
}

declare module "material-ui/internal/ClickAwayListener" {
  declare module.exports: any
}

declare module "material-ui/internal/createRippleHandler" {
  declare module.exports: any
}

declare module "material-ui/internal/Modal" {
  declare module.exports: any
}

declare module "material-ui/internal/modalManager" {
  declare module.exports: any
}

declare module "material-ui/internal/Popover" {
  declare module.exports: any
}

declare module "material-ui/internal/Portal" {
  declare module.exports: any
}

declare module "material-ui/internal/Ripple" {
  declare module.exports: any
}

declare module "material-ui/internal/SwitchBase" {
  declare module.exports: any
}

declare module "material-ui/internal/TouchRipple" {
  declare module.exports: any
}

declare module "material-ui/internal/Transition" {
  declare module.exports: any
}

declare module "material-ui/internal/withSwitchLabel" {
  declare module.exports: any
}

declare module "material-ui/List/index" {
  declare module.exports: any
}

declare module "material-ui/List/List" {
  declare module.exports: any
}

declare module "material-ui/List/ListItem" {
  declare module.exports: any
}

declare module "material-ui/List/ListItemAvatar" {
  declare module.exports: any
}

declare module "material-ui/List/ListItemIcon" {
  declare module.exports: any
}

declare module "material-ui/List/ListItemSecondaryAction" {
  declare module.exports: any
}

declare module "material-ui/List/ListItemText" {
  declare module.exports: any
}

declare module "material-ui/List/ListSubheader" {
  declare module.exports: any
}

declare module "material-ui/Menu/index" {
  declare module.exports: any
}

declare module "material-ui/Menu/Menu" {
  declare module.exports: any
}

declare module "material-ui/Menu/MenuItem" {
  declare module.exports: any
}

declare module "material-ui/Menu/MenuList" {
  declare module.exports: any
}

declare module "material-ui/MobileStepper/index" {
  declare module.exports: any
}

declare module "material-ui/MobileStepper/MobileStepper" {
  declare module.exports: any
}

declare module "material-ui/Paper/index" {
  declare module.exports: any
}

declare module "material-ui/Paper/Paper" {
  declare module.exports: any
}

declare module "material-ui/Progress/CircularProgress" {
  declare module.exports: any
}

declare module "material-ui/Progress/index" {
  declare module.exports: any
}

declare module "material-ui/Progress/LinearProgress" {
  declare module.exports: any
}

declare module "material-ui/Radio/index" {
  declare module.exports: any
}

declare module "material-ui/Radio/LabelRadio" {
  declare module.exports: any
}

declare module "material-ui/Radio/Radio" {
  declare module.exports: any
}

declare module "material-ui/Radio/RadioGroup" {
  declare module.exports: any
}

declare module "material-ui/Snackbar/index" {
  declare module.exports: any
}

declare module "material-ui/Snackbar/Snackbar" {
  declare module.exports: any
}

declare module "material-ui/Snackbar/SnackbarContent" {
  declare module.exports: any
}

declare module "material-ui/styles/breakpoints" {
  declare module.exports: any
}

declare module "material-ui/styles/colorManipulator" {
  declare module.exports: any
}

declare module "material-ui/styles/colors" {
  declare module.exports: any
}

declare module "material-ui/styles/index" {
  declare module.exports: any
}

declare module "material-ui/styles/mixins" {
  declare module.exports: any
}

declare module "material-ui/styles/MuiThemeProvider" {
  declare module.exports: any
}

declare module "material-ui/styles/muiThemeProviderFactory" {
  declare module.exports: any
}

declare module "material-ui/styles/palette" {
  declare module.exports: any
}

declare module "material-ui/styles/shadows" {
  declare module.exports: any
}

declare module "material-ui/styles/spacing" {
  declare module.exports: any
}

declare module "material-ui/styles/theme" {
  declare module.exports: any
}

declare module "material-ui/styles/transitions" {
  declare module.exports: any
}

declare module "material-ui/styles/typography" {
  declare module.exports: any
}

declare module "material-ui/styles/withStyles" {
  declare module.exports: any
}

declare module "material-ui/styles/withTheme" {
  declare module.exports: any
}

declare module "material-ui/styles/zIndex" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/arrow-downward" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/cancel" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/check-box-outline-blank" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/check-box" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/keyboard-arrow-left" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/keyboard-arrow-right" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/radio-button-checked" {
  declare module.exports: any
}

declare module "material-ui/svg-icons/radio-button-unchecked" {
  declare module.exports: any
}

declare module "material-ui/SvgIcon/index" {
  declare module.exports: any
}

declare module "material-ui/SvgIcon/SvgIcon" {
  declare module.exports: any
}

declare module "material-ui/Switch/index" {
  declare module.exports: any
}

declare module "material-ui/Switch/LabelSwitch" {
  declare module.exports: any
}

declare module "material-ui/Switch/Switch" {
  declare module.exports: any
}

declare module "material-ui/Table/index" {
  declare module.exports: any
}

declare module "material-ui/Table/Table" {
  declare module.exports: any
}

declare module "material-ui/Table/TableBody" {
  declare module.exports: any
}

declare module "material-ui/Table/TableCell" {
  declare module.exports: any
}

declare module "material-ui/Table/TableHead" {
  declare module.exports: any
}

declare module "material-ui/Table/TableRow" {
  declare module.exports: any
}

declare module "material-ui/Table/TableSortLabel" {
  declare module.exports: any
}

declare module "material-ui/Tabs/index" {
  declare module.exports: any
}

declare module "material-ui/Tabs/Tab" {
  declare module.exports: any
}

declare module "material-ui/Tabs/TabIndicator" {
  declare module.exports: any
}

declare module "material-ui/Tabs/Tabs" {
  declare module.exports: any
}

declare module "material-ui/Tabs/TabScrollButton" {
  declare module.exports: any
}

declare module "material-ui/test-utils/createMount" {
  declare module.exports: any
}

declare module "material-ui/test-utils/createRender" {
  declare module.exports: any
}

declare module "material-ui/test-utils/createShallow" {
  declare module.exports: any
}

declare module "material-ui/test-utils/index" {
  declare module.exports: any
}

declare module "material-ui/TextField/index" {
  declare module.exports: any
}

declare module "material-ui/TextField/TextField" {
  declare module.exports: any
}

declare module "material-ui/Toolbar/index" {
  declare module.exports: any
}

declare module "material-ui/Toolbar/Toolbar" {
  declare module.exports: any
}

declare module "material-ui/transitions/Collapse" {
  declare module.exports: any
}

declare module "material-ui/transitions/Fade" {
  declare module.exports: any
}

declare module "material-ui/transitions/Slide" {
  declare module.exports: any
}

declare module "material-ui/Typography/index" {
  declare module.exports: any
}

declare module "material-ui/Typography/Typography" {
  declare module.exports: any
}

declare module "material-ui/umd/material-ui.development" {
  declare module.exports: any
}

declare module "material-ui/umd/material-ui.production.min" {
  declare module.exports: any
}

declare module "material-ui/utils/addEventListener" {
  declare module.exports: any
}

declare module "material-ui/utils/customPropTypes" {
  declare module.exports: any
}

declare module "material-ui/utils/helpers" {
  declare module.exports: any
}

declare module "material-ui/utils/keyboardFocus" {
  declare module.exports: any
}

declare module "material-ui/utils/manageAriaHidden" {
  declare module.exports: any
}

declare module "material-ui/utils/reactHelpers" {
  declare module.exports: any
}

declare module "material-ui/utils/requirePropFactory" {
  declare module.exports: any
}

declare module "material-ui/utils/withWidth" {
  declare module.exports: any
}

// Filename aliases
declare module "material-ui/AppBar/AppBar.js" {
  declare module.exports: $Exports<"material-ui/AppBar/AppBar">
}
declare module "material-ui/AppBar/index.js" {
  declare module.exports: $Exports<"material-ui/AppBar/index">
}
declare module "material-ui/Avatar/Avatar.js" {
  declare module.exports: $Exports<"material-ui/Avatar/Avatar">
}
declare module "material-ui/Avatar/index.js" {
  declare module.exports: $Exports<"material-ui/Avatar/index">
}
declare module "material-ui/Badge/Badge.js" {
  declare module.exports: $Exports<"material-ui/Badge/Badge">
}
declare module "material-ui/Badge/index.js" {
  declare module.exports: $Exports<"material-ui/Badge/index">
}
declare module "material-ui/BottomNavigation/BottomNavigation.js" {
  declare module.exports: $Exports<
    "material-ui/BottomNavigation/BottomNavigation"
  >
}
declare module "material-ui/BottomNavigation/BottomNavigationButton.js" {
  declare module.exports: $Exports<
    "material-ui/BottomNavigation/BottomNavigationButton"
  >
}
declare module "material-ui/BottomNavigation/index.js" {
  declare module.exports: $Exports<"material-ui/BottomNavigation/index">
}
declare module "material-ui/Button/Button.js" {
  declare module.exports: $Exports<"material-ui/Button/Button">
}
declare module "material-ui/Button/index.js" {
  declare module.exports: $Exports<"material-ui/Button/index">
}
declare module "material-ui/Card/Card.js" {
  declare module.exports: $Exports<"material-ui/Card/Card">
}
declare module "material-ui/Card/CardActions.js" {
  declare module.exports: $Exports<"material-ui/Card/CardActions">
}
declare module "material-ui/Card/CardContent.js" {
  declare module.exports: $Exports<"material-ui/Card/CardContent">
}
declare module "material-ui/Card/CardHeader.js" {
  declare module.exports: $Exports<"material-ui/Card/CardHeader">
}
declare module "material-ui/Card/CardMedia.js" {
  declare module.exports: $Exports<"material-ui/Card/CardMedia">
}
declare module "material-ui/Card/index.js" {
  declare module.exports: $Exports<"material-ui/Card/index">
}
declare module "material-ui/Checkbox/Checkbox.js" {
  declare module.exports: $Exports<"material-ui/Checkbox/Checkbox">
}
declare module "material-ui/Checkbox/index.js" {
  declare module.exports: $Exports<"material-ui/Checkbox/index">
}
declare module "material-ui/Checkbox/LabelCheckbox.js" {
  declare module.exports: $Exports<"material-ui/Checkbox/LabelCheckbox">
}
declare module "material-ui/Chip/Chip.js" {
  declare module.exports: $Exports<"material-ui/Chip/Chip">
}
declare module "material-ui/Chip/index.js" {
  declare module.exports: $Exports<"material-ui/Chip/index">
}
declare module "material-ui/Dialog/Dialog.js" {
  declare module.exports: $Exports<"material-ui/Dialog/Dialog">
}
declare module "material-ui/Dialog/DialogActions.js" {
  declare module.exports: $Exports<"material-ui/Dialog/DialogActions">
}
declare module "material-ui/Dialog/DialogContent.js" {
  declare module.exports: $Exports<"material-ui/Dialog/DialogContent">
}
declare module "material-ui/Dialog/DialogContentText.js" {
  declare module.exports: $Exports<"material-ui/Dialog/DialogContentText">
}
declare module "material-ui/Dialog/DialogTitle.js" {
  declare module.exports: $Exports<"material-ui/Dialog/DialogTitle">
}
declare module "material-ui/Dialog/index.js" {
  declare module.exports: $Exports<"material-ui/Dialog/index">
}
declare module "material-ui/Dialog/withResponsiveFullScreen.js" {
  declare module.exports: $Exports<
    "material-ui/Dialog/withResponsiveFullScreen"
  >
}
declare module "material-ui/Divider/Divider.js" {
  declare module.exports: $Exports<"material-ui/Divider/Divider">
}
declare module "material-ui/Divider/index.js" {
  declare module.exports: $Exports<"material-ui/Divider/index">
}
declare module "material-ui/Drawer/Drawer.js" {
  declare module.exports: $Exports<"material-ui/Drawer/Drawer">
}
declare module "material-ui/Drawer/index.js" {
  declare module.exports: $Exports<"material-ui/Drawer/index">
}
declare module "material-ui/Form/FormControl.js" {
  declare module.exports: $Exports<"material-ui/Form/FormControl">
}
declare module "material-ui/Form/FormGroup.js" {
  declare module.exports: $Exports<"material-ui/Form/FormGroup">
}
declare module "material-ui/Form/FormHelperText.js" {
  declare module.exports: $Exports<"material-ui/Form/FormHelperText">
}
declare module "material-ui/Form/FormLabel.js" {
  declare module.exports: $Exports<"material-ui/Form/FormLabel">
}
declare module "material-ui/Form/index.js" {
  declare module.exports: $Exports<"material-ui/Form/index">
}
declare module "material-ui/Grid/Grid.js" {
  declare module.exports: $Exports<"material-ui/Grid/Grid">
}
declare module "material-ui/Grid/index.js" {
  declare module.exports: $Exports<"material-ui/Grid/index">
}
declare module "material-ui/Hidden/Hidden.js" {
  declare module.exports: $Exports<"material-ui/Hidden/Hidden">
}
declare module "material-ui/Hidden/HiddenJs.js" {
  declare module.exports: $Exports<"material-ui/Hidden/HiddenJs">
}
declare module "material-ui/Hidden/index.js" {
  declare module.exports: $Exports<"material-ui/Hidden/index">
}
declare module "material-ui/Hidden/types.js" {
  declare module.exports: $Exports<"material-ui/Hidden/types">
}
declare module "material-ui/Icon/Icon.js" {
  declare module.exports: $Exports<"material-ui/Icon/Icon">
}
declare module "material-ui/Icon/index.js" {
  declare module.exports: $Exports<"material-ui/Icon/index">
}
declare module "material-ui/IconButton/IconButton.js" {
  declare module.exports: $Exports<"material-ui/IconButton/IconButton">
}
declare module "material-ui/IconButton/index.js" {
  declare module.exports: $Exports<"material-ui/IconButton/index">
}
declare module "material-ui/index.es.js" {
  declare module.exports: $Exports<"material-ui/index.es">
}
declare module "material-ui/index" {
  declare module.exports: $Exports<"material-ui">
}
declare module "material-ui/index.js" {
  declare module.exports: $Exports<"material-ui">
}
declare module "material-ui/Input/index.js" {
  declare module.exports: $Exports<"material-ui/Input/index">
}
declare module "material-ui/Input/Input.js" {
  declare module.exports: $Exports<"material-ui/Input/Input">
}
declare module "material-ui/Input/InputLabel.js" {
  declare module.exports: $Exports<"material-ui/Input/InputLabel">
}
declare module "material-ui/Input/Textarea.js" {
  declare module.exports: $Exports<"material-ui/Input/Textarea">
}
declare module "material-ui/internal/Backdrop.js" {
  declare module.exports: $Exports<"material-ui/internal/Backdrop">
}
declare module "material-ui/internal/ButtonBase.js" {
  declare module.exports: $Exports<"material-ui/internal/ButtonBase">
}
declare module "material-ui/internal/ClickAwayListener.js" {
  declare module.exports: $Exports<"material-ui/internal/ClickAwayListener">
}
declare module "material-ui/internal/createRippleHandler.js" {
  declare module.exports: $Exports<"material-ui/internal/createRippleHandler">
}
declare module "material-ui/internal/Modal.js" {
  declare module.exports: $Exports<"material-ui/internal/Modal">
}
declare module "material-ui/internal/modalManager.js" {
  declare module.exports: $Exports<"material-ui/internal/modalManager">
}
declare module "material-ui/internal/Popover.js" {
  declare module.exports: $Exports<"material-ui/internal/Popover">
}
declare module "material-ui/internal/Portal.js" {
  declare module.exports: $Exports<"material-ui/internal/Portal">
}
declare module "material-ui/internal/Ripple.js" {
  declare module.exports: $Exports<"material-ui/internal/Ripple">
}
declare module "material-ui/internal/SwitchBase.js" {
  declare module.exports: $Exports<"material-ui/internal/SwitchBase">
}
declare module "material-ui/internal/TouchRipple.js" {
  declare module.exports: $Exports<"material-ui/internal/TouchRipple">
}
declare module "material-ui/internal/Transition.js" {
  declare module.exports: $Exports<"material-ui/internal/Transition">
}
declare module "material-ui/internal/withSwitchLabel.js" {
  declare module.exports: $Exports<"material-ui/internal/withSwitchLabel">
}
declare module "material-ui/List/index.js" {
  declare module.exports: $Exports<"material-ui/List/index">
}
declare module "material-ui/List/List.js" {
  declare module.exports: $Exports<"material-ui/List/List">
}
declare module "material-ui/List/ListItem.js" {
  declare module.exports: $Exports<"material-ui/List/ListItem">
}
declare module "material-ui/List/ListItemAvatar.js" {
  declare module.exports: $Exports<"material-ui/List/ListItemAvatar">
}
declare module "material-ui/List/ListItemIcon.js" {
  declare module.exports: $Exports<"material-ui/List/ListItemIcon">
}
declare module "material-ui/List/ListItemSecondaryAction.js" {
  declare module.exports: $Exports<"material-ui/List/ListItemSecondaryAction">
}
declare module "material-ui/List/ListItemText.js" {
  declare module.exports: $Exports<"material-ui/List/ListItemText">
}
declare module "material-ui/List/ListSubheader.js" {
  declare module.exports: $Exports<"material-ui/List/ListSubheader">
}
declare module "material-ui/Menu/index.js" {
  declare module.exports: $Exports<"material-ui/Menu/index">
}
declare module "material-ui/Menu/Menu.js" {
  declare module.exports: $Exports<"material-ui/Menu/Menu">
}
declare module "material-ui/Menu/MenuItem.js" {
  declare module.exports: $Exports<"material-ui/Menu/MenuItem">
}
declare module "material-ui/Menu/MenuList.js" {
  declare module.exports: $Exports<"material-ui/Menu/MenuList">
}
declare module "material-ui/MobileStepper/index.js" {
  declare module.exports: $Exports<"material-ui/MobileStepper/index">
}
declare module "material-ui/MobileStepper/MobileStepper.js" {
  declare module.exports: $Exports<"material-ui/MobileStepper/MobileStepper">
}
declare module "material-ui/Paper/index.js" {
  declare module.exports: $Exports<"material-ui/Paper/index">
}
declare module "material-ui/Paper/Paper.js" {
  declare module.exports: $Exports<"material-ui/Paper/Paper">
}
declare module "material-ui/Progress/CircularProgress.js" {
  declare module.exports: $Exports<"material-ui/Progress/CircularProgress">
}
declare module "material-ui/Progress/index.js" {
  declare module.exports: $Exports<"material-ui/Progress/index">
}
declare module "material-ui/Progress/LinearProgress.js" {
  declare module.exports: $Exports<"material-ui/Progress/LinearProgress">
}
declare module "material-ui/Radio/index.js" {
  declare module.exports: $Exports<"material-ui/Radio/index">
}
declare module "material-ui/Radio/LabelRadio.js" {
  declare module.exports: $Exports<"material-ui/Radio/LabelRadio">
}
declare module "material-ui/Radio/Radio.js" {
  declare module.exports: $Exports<"material-ui/Radio/Radio">
}
declare module "material-ui/Radio/RadioGroup.js" {
  declare module.exports: $Exports<"material-ui/Radio/RadioGroup">
}
declare module "material-ui/Snackbar/index.js" {
  declare module.exports: $Exports<"material-ui/Snackbar/index">
}
declare module "material-ui/Snackbar/Snackbar.js" {
  declare module.exports: $Exports<"material-ui/Snackbar/Snackbar">
}
declare module "material-ui/Snackbar/SnackbarContent.js" {
  declare module.exports: $Exports<"material-ui/Snackbar/SnackbarContent">
}
declare module "material-ui/styles/breakpoints.js" {
  declare module.exports: $Exports<"material-ui/styles/breakpoints">
}
declare module "material-ui/styles/colorManipulator.js" {
  declare module.exports: $Exports<"material-ui/styles/colorManipulator">
}
declare module "material-ui/styles/colors.js" {
  declare module.exports: $Exports<"material-ui/styles/colors">
}
declare module "material-ui/styles/index.js" {
  declare module.exports: $Exports<"material-ui/styles/index">
}
declare module "material-ui/styles/mixins.js" {
  declare module.exports: $Exports<"material-ui/styles/mixins">
}
declare module "material-ui/styles/MuiThemeProvider.js" {
  declare module.exports: $Exports<"material-ui/styles/MuiThemeProvider">
}
declare module "material-ui/styles/muiThemeProviderFactory.js" {
  declare module.exports: $Exports<"material-ui/styles/muiThemeProviderFactory">
}
declare module "material-ui/styles/palette.js" {
  declare module.exports: $Exports<"material-ui/styles/palette">
}
declare module "material-ui/styles/shadows.js" {
  declare module.exports: $Exports<"material-ui/styles/shadows">
}
declare module "material-ui/styles/spacing.js" {
  declare module.exports: $Exports<"material-ui/styles/spacing">
}
declare module "material-ui/styles/theme.js" {
  declare module.exports: $Exports<"material-ui/styles/theme">
}
declare module "material-ui/styles/transitions.js" {
  declare module.exports: $Exports<"material-ui/styles/transitions">
}
declare module "material-ui/styles/typography.js" {
  declare module.exports: $Exports<"material-ui/styles/typography">
}
declare module "material-ui/styles/withStyles.js" {
  declare module.exports: $Exports<"material-ui/styles/withStyles">
}
declare module "material-ui/styles/withTheme.js" {
  declare module.exports: $Exports<"material-ui/styles/withTheme">
}
declare module "material-ui/styles/zIndex.js" {
  declare module.exports: $Exports<"material-ui/styles/zIndex">
}
declare module "material-ui/svg-icons/arrow-downward.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/arrow-downward">
}
declare module "material-ui/svg-icons/cancel.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/cancel">
}
declare module "material-ui/svg-icons/check-box-outline-blank.js" {
  declare module.exports: $Exports<
    "material-ui/svg-icons/check-box-outline-blank"
  >
}
declare module "material-ui/svg-icons/check-box.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/check-box">
}
declare module "material-ui/svg-icons/keyboard-arrow-left.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/keyboard-arrow-left">
}
declare module "material-ui/svg-icons/keyboard-arrow-right.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/keyboard-arrow-right">
}
declare module "material-ui/svg-icons/radio-button-checked.js" {
  declare module.exports: $Exports<"material-ui/svg-icons/radio-button-checked">
}
declare module "material-ui/svg-icons/radio-button-unchecked.js" {
  declare module.exports: $Exports<
    "material-ui/svg-icons/radio-button-unchecked"
  >
}
declare module "material-ui/SvgIcon/index.js" {
  declare module.exports: $Exports<"material-ui/SvgIcon/index">
}
declare module "material-ui/SvgIcon/SvgIcon.js" {
  declare module.exports: $Exports<"material-ui/SvgIcon/SvgIcon">
}
declare module "material-ui/Switch/index.js" {
  declare module.exports: $Exports<"material-ui/Switch/index">
}
declare module "material-ui/Switch/LabelSwitch.js" {
  declare module.exports: $Exports<"material-ui/Switch/LabelSwitch">
}
declare module "material-ui/Switch/Switch.js" {
  declare module.exports: $Exports<"material-ui/Switch/Switch">
}
declare module "material-ui/Table/index.js" {
  declare module.exports: $Exports<"material-ui/Table/index">
}
declare module "material-ui/Table/Table.js" {
  declare module.exports: $Exports<"material-ui/Table/Table">
}
declare module "material-ui/Table/TableBody.js" {
  declare module.exports: $Exports<"material-ui/Table/TableBody">
}
declare module "material-ui/Table/TableCell.js" {
  declare module.exports: $Exports<"material-ui/Table/TableCell">
}
declare module "material-ui/Table/TableHead.js" {
  declare module.exports: $Exports<"material-ui/Table/TableHead">
}
declare module "material-ui/Table/TableRow.js" {
  declare module.exports: $Exports<"material-ui/Table/TableRow">
}
declare module "material-ui/Table/TableSortLabel.js" {
  declare module.exports: $Exports<"material-ui/Table/TableSortLabel">
}
declare module "material-ui/Tabs/index.js" {
  declare module.exports: $Exports<"material-ui/Tabs/index">
}
declare module "material-ui/Tabs/Tab.js" {
  declare module.exports: $Exports<"material-ui/Tabs/Tab">
}
declare module "material-ui/Tabs/TabIndicator.js" {
  declare module.exports: $Exports<"material-ui/Tabs/TabIndicator">
}
declare module "material-ui/Tabs/Tabs.js" {
  declare module.exports: $Exports<"material-ui/Tabs/Tabs">
}
declare module "material-ui/Tabs/TabScrollButton.js" {
  declare module.exports: $Exports<"material-ui/Tabs/TabScrollButton">
}
declare module "material-ui/test-utils/createMount.js" {
  declare module.exports: $Exports<"material-ui/test-utils/createMount">
}
declare module "material-ui/test-utils/createRender.js" {
  declare module.exports: $Exports<"material-ui/test-utils/createRender">
}
declare module "material-ui/test-utils/createShallow.js" {
  declare module.exports: $Exports<"material-ui/test-utils/createShallow">
}
declare module "material-ui/test-utils/index.js" {
  declare module.exports: $Exports<"material-ui/test-utils/index">
}
declare module "material-ui/TextField/index.js" {
  declare module.exports: $Exports<"material-ui/TextField/index">
}
declare module "material-ui/TextField/TextField.js" {
  declare module.exports: $Exports<"material-ui/TextField/TextField">
}
declare module "material-ui/Toolbar/index.js" {
  declare module.exports: $Exports<"material-ui/Toolbar/index">
}
declare module "material-ui/Toolbar/Toolbar.js" {
  declare module.exports: $Exports<"material-ui/Toolbar/Toolbar">
}
declare module "material-ui/transitions/Collapse.js" {
  declare module.exports: $Exports<"material-ui/transitions/Collapse">
}
declare module "material-ui/transitions/Fade.js" {
  declare module.exports: $Exports<"material-ui/transitions/Fade">
}
declare module "material-ui/transitions/Slide.js" {
  declare module.exports: $Exports<"material-ui/transitions/Slide">
}
declare module "material-ui/Typography/index.js" {
  declare module.exports: $Exports<"material-ui/Typography/index">
}
declare module "material-ui/Typography/Typography.js" {
  declare module.exports: $Exports<"material-ui/Typography/Typography">
}
declare module "material-ui/umd/material-ui.development.js" {
  declare module.exports: $Exports<"material-ui/umd/material-ui.development">
}
declare module "material-ui/umd/material-ui.production.min.js" {
  declare module.exports: $Exports<"material-ui/umd/material-ui.production.min">
}
declare module "material-ui/utils/addEventListener.js" {
  declare module.exports: $Exports<"material-ui/utils/addEventListener">
}
declare module "material-ui/utils/customPropTypes.js" {
  declare module.exports: $Exports<"material-ui/utils/customPropTypes">
}
declare module "material-ui/utils/helpers.js" {
  declare module.exports: $Exports<"material-ui/utils/helpers">
}
declare module "material-ui/utils/keyboardFocus.js" {
  declare module.exports: $Exports<"material-ui/utils/keyboardFocus">
}
declare module "material-ui/utils/manageAriaHidden.js" {
  declare module.exports: $Exports<"material-ui/utils/manageAriaHidden">
}
declare module "material-ui/utils/reactHelpers.js" {
  declare module.exports: $Exports<"material-ui/utils/reactHelpers">
}
declare module "material-ui/utils/requirePropFactory.js" {
  declare module.exports: $Exports<"material-ui/utils/requirePropFactory">
}
declare module "material-ui/utils/withWidth.js" {
  declare module.exports: $Exports<"material-ui/utils/withWidth">
}
